### ISSUE TITLE
TrueBeam v3.0 MPC Changes

### ISSUE THREAD

**Issue by ash-cullen** [qatrackplus/qcpump#11]
TrueBeam v3.0 has some changes to MPC, and what was previously called "Enhanced MLC Check" is now called "Collimation Devices Check". This includes some additional jaw tests where jaw position is tested at 4 different positions per jaw, as well as a determination of jaw parallelism (in degrees) at each position, along with max parallelism for each jaw.

While existing MLC metrics appear unchanged, the folder naming convention has now changed from EnhancedMLCCheckTemplate6x to CollimationDevicesCheckTemplate6x

**Comment by ash-cullen** [comment]
Apologies, incorrect Results.csv file attached. Correct one below:
[Results.csv](https://github.com/qatrackplus/qcpump/files/11944356/Results.csv)

**Comment by ash-cullen** [comment]
Changes made to mpc.py here: https://github.com/ash-cullen/qcpump/commit/bb1b1cac7085e979bcfeeef44ab57a171747804b

I tested this and these changes work at my hospital.

Note that new tests need to be created as checks are under the CollimationDevicesGroup, and MLCs are tests at 3 positions.

**Comment by randlet** [comment]
Thanks so much Ash!   I'll apply that fix and get a new release out soon.

**Comment by randlet** [comment]
Updated in v0.3.15. Thanks again.
