### ISSUE TITLE
qcpump for FFF beams with new DQA3 sql database

### ISSUE THREAD

**Issue by dean-wilkinson** [qatrackplus/qcpump#5]
In the process of testing qcpump with the SQL DQA3 v1.06 database I came across a feature in the new database which is different from the previous Firebird SQL database for measuring QA beam flatness on a FFF beam.

In the SQL version of the database, rather than measuring QA flatness for FFF beams it reports a different parameter BSC (beam shape constancy - see screenshot attached).  This value resides in a different column to QA Flatness in the DQA3_TREND table in the DB schema and the reported QA Flatness value is 0.00 which is what comes across with the qcpump.  If i have interpreted correctly, the BSC value column is RESULTS_BCS2 in the DQA3_TREND table in the SQL database.

Is it possible to modify the QC pump code to point to this BSC parameter in the table for FFF beams?

![BSC_DQA3](https://user-images.githubusercontent.com/107463751/173522220-3285e80b-2659-4fa4-b3a6-662a59a17912.PNG)
)

**Comment by randlet** [comment]
Hi @dean-wilkinson, thanks for the heads up on that!  I added all the bsc{1,2,3} columns for the next release (being released shortly).

**Comment by randlet** [comment]
Resolved in 84e9f1ddd09cd3d

**Comment by dean-wilkinson** [comment]
Thanks Randy! Fantastic that it is already available in the next release :)
