### ISSUE TITLE
Request: Change default setting to include comments

### ISSUE THREAD

**Issue by tbezo** [qatrackplus/qcpump#8]
Hi,
my personal opinion: I would be better to include comments by default.
Yesterday I had a short debug session because the "add norm to comment" function of my ptwqcpump was not working anymore with the new version of qcpump.

**Comment by randlet** [comment]
Thanks for the feedback and sorry for the confusion.  I don't mind reverting back to the old behaviour.  Really I think the ultimate solution is to resolve this issue in QATrack+ https://github.com/qatrackplus/qatrackplus/issues/476

**Comment by randlet** [comment]
Resolved in v0.3.15
